
const INC_CUS = "INC_CUS";
const INC = "INC";
const DEC = "DEC";
const RESET = "RESET";

const INC_CUS2 = "INC_CUS2";
const INC2 = "INC2";
const DEC2 = "DEC2";
const RESET2 = "RESET2";

const ON_USERS_LOAD = 'ON_USERS_LOAD';
const ON_ADD_TO_BAD = 'ON_ADD_TO_BAD';
const ON_REMOVE_FROM_BAD = 'ON_REMOVE_FROM_BAD';

const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING';
const SET_PRODUCTS = 'SET_PRODUCTS';


const ADD_PRODUCT = 'ADD_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const ADD_WISHLIST = 'ADD_WISHLIST';
const REMOVE_WISHLIST = 'REMOVE_WISHLIST';

export {
    INC_CUS,
    INC,
    DEC,
    RESET,
    INC_CUS2,
    INC2,
    DEC2,
    RESET2,
    ON_USERS_LOAD,
    ON_ADD_TO_BAD,
    ON_REMOVE_FROM_BAD,
    START_PRODUCTS_LOADING,
    END_PRODUCTS_LOADING,
    SET_PRODUCTS,
    ADD_PRODUCT,
    REMOVE_PRODUCT,
    ADD_WISHLIST,
    REMOVE_WISHLIST
}
